version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - collabo-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - collabo-net
    depends_on:
      - backend

networks:
  collabo-net:
    driver: bridge